"""initial

Revision ID: 7cf8e5172f60
Revises: None
Create Date: 2026-06-06 04:45:47.253023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7cf8e5172f60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comic_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comic_year', sa.Integer(), nullable=True),
    sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comic_comic_id'), 'comic', ['comic_id'], unique=True)
    op.create_table('failed_release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_failed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_release_comic_id'), 'failed_release', ['comic_id'], unique=False)
    op.create_index(op.f('ix_failed_release_issue_id'), 'failed_release', ['issue_id'], unique=False)
    op.create_index(op.f('ix_failed_release_release_id'), 'failed_release', ['release_id'], unique=True)
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('release_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_comic_id'), 'issue', ['comic_id'], unique=False)
    op.create_index(op.f('ix_issue_issue_id'), 'issue', ['issue_id'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('COMICVINE_API_KEY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('COMICVINE_API_URL', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('CV_USER_AGENT', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('CVAPI_RATE', sa.Float(), nullable=False),
    sa.Column('CV_VERIFY', sa.Boolean(), nullable=False),
    sa.Column('CACHE_DIR', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('DESTINATION_DIR', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('CREATE_FOLDERS', sa.Boolean(), nullable=False),
    sa.Column('COMIC_COVER_LOCAL', sa.Boolean(), nullable=False),
    sa.Column('COVER_FOLDER_LOCAL', sa.Boolean(), nullable=False),
    sa.Column('NEWZNAB_PROVIDERS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('TORZNAB_PROVIDERS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('SEARCH_INTERVAL_MINUTES', sa.Integer(), nullable=False),
    sa.Column('GRAB_ON_MATCH', sa.Boolean(), nullable=False),
    sa.Column('CV_SYNC_INTERVAL_HOURS', sa.Integer(), nullable=False),
    sa.Column('DOWNLOADER_TYPE', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('SABNZBD_URL', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('SABNZBD_API_KEY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('SABNZBD_CATEGORY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('NZBGET_URL', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('NZBGET_USERNAME', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('NZBGET_PASSWORD', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('NZBGET_CATEGORY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('QBITTORRENT_URL', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('QBITTORRENT_USERNAME', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('QBITTORRENT_PASSWORD', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('QBITTORRENT_CATEGORY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('TRANSMISSION_URL', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('TRANSMISSION_USERNAME', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('TRANSMISSION_PASSWORD', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('TRANSMISSION_DIRECTORY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('APPRISE_URLS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('NOTIFY_ON_SNATCH', sa.Boolean(), nullable=False),
    sa.Column('NOTIFY_ON_FAILURE', sa.Boolean(), nullable=False),
    sa.Column('NOTIFY_ON_NEW_ISSUES', sa.Boolean(), nullable=False),
    sa.Column('FAILED_DOWNLOAD_HANDLING', sa.Boolean(), nullable=False),
    sa.Column('FAILED_AUTO', sa.Boolean(), nullable=False),
    sa.Column('FILE_FORMAT', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('FOLDER_FORMAT', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('MOVE_FILES', sa.Boolean(), nullable=False),
    sa.Column('RENAME_FILES', sa.Boolean(), nullable=False),
    sa.Column('PREFERRED_QUALITY', sa.Integer(), nullable=False),
    sa.Column('ENABLE_PUBLIC', sa.Boolean(), nullable=False),
    sa.Column('ENABLE_TORRENTS', sa.Boolean(), nullable=False),
    sa.Column('ENABLE_TORRENT_SEARCH', sa.Boolean(), nullable=False),
    sa.Column('MINSEEDS', sa.Integer(), nullable=False),
    sa.Column('PUBLIC_VERIFY', sa.Boolean(), nullable=False),
    sa.Column('WEEKLY_PULL_PROXY_URL', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ALT_PULL', sa.Integer(), nullable=False),
    sa.Column('AUTO_MASS_ADD', sa.Boolean(), nullable=False),
    sa.Column('BIGGIE_PUB', sa.Integer(), nullable=False),
    sa.Column('INDIE_PUB', sa.Integer(), nullable=False),
    sa.Column('MASS_PUBLISHERS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('PACK_0DAY_WATCHLIST_ONLY', sa.Boolean(), nullable=False),
    sa.Column('PULL_REFRESH', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('RESET_PULLIST_PAGINATION', sa.Boolean(), nullable=False),
    sa.Column('WEEKFOLDER', sa.Boolean(), nullable=False),
    sa.Column('WEEKFOLDER_FORMAT', sa.Integer(), nullable=False),
    sa.Column('WEEKFOLDER_LOC', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ARC_FILEOPS', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ARC_FILEOPS_SOFTLINK_RELATIVE', sa.Boolean(), nullable=False),
    sa.Column('ARC_FOLDERFORMAT', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('COPY2ARCDIR', sa.Boolean(), nullable=False),
    sa.Column('SEARCH_STORYARCS', sa.Boolean(), nullable=False),
    sa.Column('STORYARCDIR', sa.Boolean(), nullable=False),
    sa.Column('STORYARC_LOCATION', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('UPCOMING_STORYARCS', sa.Boolean(), nullable=False),
    sa.Column('CBR2CBZ_ONLY', sa.Boolean(), nullable=False),
    sa.Column('CMTAGGER_PATH', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('CMTAG_START_YEAR_AS_VOLUME', sa.Boolean(), nullable=False),
    sa.Column('CMTAG_VOLUME', sa.Boolean(), nullable=False),
    sa.Column('CT_CBZ_OVERWRITE', sa.Boolean(), nullable=False),
    sa.Column('CT_NOTES_FORMAT', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('CT_SETTINGSPATH', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('CT_TAG_CBL', sa.Boolean(), nullable=False),
    sa.Column('CT_TAG_CR', sa.Boolean(), nullable=False),
    sa.Column('CV_BATCH_LIMIT_PROTECTION', sa.Boolean(), nullable=False),
    sa.Column('CV_BATCH_LIMIT_THRESHOLD', sa.Integer(), nullable=False),
    sa.Column('ENABLE_META', sa.Boolean(), nullable=False),
    sa.Column('SETDEFAULTVOLUME', sa.Boolean(), nullable=False),
    sa.Column('UNRAR_CMD', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('DDL_AUTORESUME', sa.Boolean(), nullable=False),
    sa.Column('DDL_LOCATION', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('DDL_PREFER_UPSCALED', sa.Boolean(), nullable=False),
    sa.Column('DDL_PRIORITY_ORDER', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('DDL_QUERY_DELAY', sa.Integer(), nullable=False),
    sa.Column('ENABLE_DDL', sa.Boolean(), nullable=False),
    sa.Column('ENABLE_EXTERNAL_SERVER', sa.Boolean(), nullable=False),
    sa.Column('ENABLE_FLARESOLVERR', sa.Boolean(), nullable=False),
    sa.Column('ENABLE_GETCOMICS', sa.Boolean(), nullable=False),
    sa.Column('ENABLE_PROXY', sa.Boolean(), nullable=False),
    sa.Column('EXTERNAL_APIKEY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('EXTERNAL_SERVER', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('EXTERNAL_USERNAME', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('FLARESOLVERR_URL', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('HTTP_PROXY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('HTTPS_PROXY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('JD2_DEST_DIR', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('JD2_ENABLE', sa.Boolean(), nullable=False),
    sa.Column('JD2_URL', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('PACK_PRIORITY', sa.Boolean(), nullable=False),
    sa.Column('SAB_CLIENT_POST_PROCESSING', sa.Boolean(), nullable=False),
    sa.Column('SAB_DIRECTORY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('SAB_MOVING_DELAY', sa.Integer(), nullable=False),
    sa.Column('SAB_PASSWORD', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('SAB_PRIORITY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('SAB_REMOVE_COMPLETED', sa.Boolean(), nullable=False),
    sa.Column('SAB_REMOVE_FAILED', sa.Boolean(), nullable=False),
    sa.Column('SAB_TO_COMICARR', sa.Boolean(), nullable=False),
    sa.Column('SAB_USERNAME', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('SAB_VERSION', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('NZBGET_CLIENT_POST_PROCESSING', sa.Boolean(), nullable=False),
    sa.Column('NZBGET_DIRECTORY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('NZBGET_PORT', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('NZBGET_PRIORITY', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('NZBGET_SUB', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('QBITTORRENT_FOLDER', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('QBITTORRENT_LABEL', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('QBITTORRENT_LOADACTION', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('TRANSMISSION_HOST', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipdate', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issue', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cv_last_update', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dynamic_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weeknumber', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('volume', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seriesyear', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('annuallink', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_issue_issue_id'), table_name='issue')
    op.drop_index(op.f('ix_issue_comic_id'), table_name='issue')
    op.drop_table('issue')
    op.drop_index(op.f('ix_failed_release_release_id'), table_name='failed_release')
    op.drop_index(op.f('ix_failed_release_issue_id'), table_name='failed_release')
    op.drop_index(op.f('ix_failed_release_comic_id'), table_name='failed_release')
    op.drop_table('failed_release')
    op.drop_index(op.f('ix_comic_comic_id'), table_name='comic')
    op.drop_table('comic')
    # ### end Alembic commands ###
