"""add_multi_downloader_settings

Revision ID: d8743223d020
Revises: 7bd4e7393877
Create Date: 2026-06-07 03:37:59.799812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd8743223d020'
down_revision: Union[str, None] = '7bd4e7393877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('SABNZBD_ENABLED', sa.Boolean(), nullable=False))
    op.add_column('system_settings', sa.Column('NZBGET_ENABLED', sa.Boolean(), nullable=False))
    op.add_column('system_settings', sa.Column('QBITTORRENT_ENABLED', sa.Boolean(), nullable=False))
    op.add_column('system_settings', sa.Column('TRANSMISSION_ENABLED', sa.Boolean(), nullable=False))
    op.add_column('system_settings', sa.Column('USENET_PREFERENCE', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('system_settings', sa.Column('TORRENT_PREFERENCE', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'TORRENT_PREFERENCE')
    op.drop_column('system_settings', 'USENET_PREFERENCE')
    op.drop_column('system_settings', 'TRANSMISSION_ENABLED')
    op.drop_column('system_settings', 'QBITTORRENT_ENABLED')
    op.drop_column('system_settings', 'NZBGET_ENABLED')
    op.drop_column('system_settings', 'SABNZBD_ENABLED')
    # ### end Alembic commands ###
